# Generated by Django 4.2.5 on 2023-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Carusel title')),
                ('name', models.CharField(max_length=100, verbose_name='Carusel name')),
                ('about', models.TextField(verbose_name='Carusel text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Carusel image')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Carusel logo')),
            ],
        ),
    ]
