# Generated by Django 4.2.5 on 2023-09-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.BooleanField(verbose_name='Product sale')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('sale_logo', models.ImageField(upload_to='', verbose_name='Sale logo')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_prod', to='main.subcategory')),
            ],
        ),
    ]
