# Generated by Django 4.2.5 on 2023-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=1, verbose_name='New product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_logo',
            field=models.ImageField(default=1, upload_to='', verbose_name='new logo'),
            preserve_default=False,
        ),
    ]
