# Generated by Django 4.2.5 on 2023-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_new_product_new_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Product add date'),
        ),
    ]
