# Generated by Django 4.2.5 on 2023-10-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Filter name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Filter_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Filter product name')),
                ('price', models.PositiveIntegerField(verbose_name='Filter product price')),
                ('img', models.ImageField(upload_to='images', verbose_name='Filter product image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_prod', to='main.filter')),
            ],
        ),
    ]
