# Generated by Django 4.2.5 on 2023-10-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_katergorianer_entakategorianer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('subject', models.TextField(verbose_name='Contact subject')),
                ('message', models.TextField(verbose_name='Contact message')),
            ],
        ),
        migrations.DeleteModel(
            name='EntaKategorianer',
        ),
        migrations.DeleteModel(
            name='Katergorianer',
        ),
    ]
